## Εργασία 1 ##

Καλωσήρθατε στην πρώτη σας εργασία. Η εργασία αυτή έχει σκοπό να σας βοηθήσει να εμπεδώσετε τα γραμμικά μοντέλα.

Τα Jupyter Notebooks είναι αλληλεπιδραστικά περιβάλλοντα προγραμματισμού ενσωματωμένα σε μια ιστοσελίδα. Στο μάθημα "Μηχανική Μάθηση" τα χρησιμοποιούμε στο πρακτικό μέρος του μαθήματος.

Στην εργασία αυτή θα πρέπει να συμπληρώσετε κώδικα Python 3 στα σημεία που αναφέρουν # YOUR CODE HERE. Μην τροποποιείτε τον κώδικα που βρίσκεται εκτός αυτών των περιοχών.

Πρωτού παραδόσετε την εργασία σας σιγουρευτείτε ότι ο κώδικας σε όλα τα κελιά τρέχει σωστά. Για το σκοπό αυτό επιλέξτε από το μενού **Χρόνος εκτέλεσης (runtime) -> Επανεκίνηση περιόδου λειτουργίας και εκτέλεση όλων**.

Συμπληρώστε το όνομα (**NAME**) και το **AEM** σας παρακάτω:

In [15]:
NAME = "Ioannidis Georgios"
AEM = "10490"

---
## Μέρος A: NumPy (1 μονάδα)

Η βιβλιοθήκη [**NumPy**](https://numpy.org/) είναι η βασική βιβιλιοθήκη για επιστημονικούς υπολογισμούς σε Python. Παρέχει ένα υψηλής επίδοσης αντικείμενο για την αποθήκευση πολυδιάστατων πινάκων και εργαλεία για επεξεργασίας αυτών των πινάκων.

Μπορείτε να συμβουλεύεστε την τεκμηρίωση ([NumPy Doc](https://numpy.org/doc/1.18/user/quickstart.html)) αυτών των βιβλιοθηκών κατά την εκπόνηση της εργασίας.

Κατά σύμβαση πάντα φορτώνουμε τη βιβλιοθήκη με τον ακόλουθο τρόπο:

In [16]:
# Run this cell
import numpy as np

**A1**: Ορίστε συνάρτηση που επιστρέφει πίνακα 2 διδαστάσεων με r γραμμές και c στήλες και περιέχει τυχαίες τιμές από 0 έως 1 με τη βοήθεια της συνάρτησης np.random.rand. Ακολουθούν τεστ ορθής λειτουργίας της συνάρτησης.

In [17]:
def random_2d_array(r, c):
    """Επιστρέφει διδιάστατο πίνακα με r γραμμές και c στήλες."""
    # YOUR CODE HERE
    result = np.random.rand(r,c)
    return result
    raise NotImplementedError()


In [18]:
"""Τεστ επιστροφής πίνακα με τις σωστές διαστάσεις"""
assert np.shape(random_2d_array(3, 5)) == (3, 5)
assert np.shape(random_2d_array(5, 2)) == (5, 2)

**A2**: Ορίστε συνάρτηση που δέχεται δύο διδιάστατους πίνακες και επιστρέφει το γινόμενο του ανάστροφου του 1ου πίνακα με τον 2ο πίνακα με τη χρήση της numpy. Ακολουθούν τεστ ορθής λειτουργίας της συνάρτησης.

In [19]:
def multiply_transpose(a, b):
    """Επιστρέφει το γινόμενο του ανάστροφου του 1ου πίνακα με τον 2ο πίνακα.
    """
    # YOUR CODE HERE
    result = a.T.dot(b)
    return result

In [20]:
"""Τεστ επιστροφής πίνακα με τις σωστές διαστάσεις"""
a = random_2d_array(3, 5)
b = random_2d_array(3, 2)
assert np.shape(multiply_transpose(a, b)) == (5, 2)
assert np.shape(multiply_transpose(b, a)) == (2, 5)

## Μέρος Β: Γραμμικά μοντέλα (6 μονάδες) ##

Σε αυτό το μέρος της άσκησης θα χτίσουμε ένα μοντέλο γραμμικής παλινδρόμησης από το μηδέν.

**B1:** Υλοποιήστε τη σιγμοειδή συνάρτηση $\sigma(z)= \dfrac{1}{1 + exp(-z)}$ με τη NumPy. Ακολουθούν τεστ ορθής λειτουργίας της συνάρτησης.

In [21]:
def sigmoid(z):
    """Υπολογίζει τη σιγμοειδή συνάρτηση."""
    # YOUR CODE HERE
    result =  1/(1+np.exp(-z))
    return result

In [22]:
"""Τεστ ορθού υπολογισμού σιγμοειδούς."""
assert sigmoid(0) == 0.5
assert np.round(sigmoid(7),8) == 0.99908895
assert np.round(sigmoid(-1),8) == 0.26894142

**B2:** Υλοποιήστε κλάση για τον αλγόριθμο της λογιστικής παλινδρόμησης. Αρχικοποιήστε τις παραμέτρους σε μηδενικές τιμές. Αποθηκεύστε τες στο διάνυσμα στήλη theta. Η συνάρτηση fit πρέπει να δέχεται πίνακα X με τις τιμές των μεταβλητών εισόδου και διάνυσμα στήλη y με τις τιμές της μεταβλητής εξόδου. Η συνάρτηση predict πρέπει να δέχεται πίνακα Χ με τις τιμές των μεταβλητών εισόδου. Ακολουθούν τεστ ορθής λειτουργίας των συναρτήσεων.

In [23]:
class MyLogisticRegression:
    def __init__(self, num_iterations=2000, learning_rate=0.004):
      self.theta = None
      self.num_iterations = num_iterations
      self.learning_rate = learning_rate

    def fit(self, X, y):
       m, n = X.shape
       X = np.concatenate((np.ones((m, 1)), X), axis=1)  # Προσθήκη της στήλης με τιμές 1 στην αρχή του X
       self.theta = np.zeros((n+1, 1))

       for _ in range(self.num_iterations):
           self.theta = self.theta - self.learning_rate * (1 / m) * (X.T @ (self.sigmoid(X @ self.theta) - y))  #hθ(x(i)) = (self.sigmoid(X @ self.theta) - y)


    def predict(self, X):
        m = X.shape[0]
        X = np.concatenate((np.ones((m, 1)), X), axis=1)  # Προσθήκη της στήλης με τιμές 1 στην αρχή του X
        z = np.dot(X, self.theta)
        probabilities = self.sigmoid(z)
        predictions = (probabilities >= 0.5).astype(int) # sigmoid --> Threshold 0.5
        return predictions


    def sigmoid(self,z):
          # YOUR CODE HERE
          result =  1/(1+np.exp(-z))
          return result

In [24]:
from sklearn.datasets import make_blobs

# δημιουργία δύο ομάδων από τυχαία σημεία με κέντρο 0,0,0 και 3,3,3 και τυπική απόκλιση 1
centers = [[0.0, 0.0, 0.0], [3.0, 3.0, 3.0]]
X, y = make_blobs(n_samples=200, centers=centers,
                  random_state=47, shuffle=False)
y = np.array(y).reshape(-1,1)

lr = MyLogisticRegression()
lr.fit(X, y)
# Εκτύπωση των αποτελεσμάτων
print("Προβλεπόμενο theta:")
print(lr.theta)
assert np.allclose(lr.theta, np.array([[-1.1772064],[0.5026043],[0.40811666],[0.55685573]]))

Προβλεπόμενο theta:
[[-1.1772064 ]
 [ 0.5026043 ]
 [ 0.40811666]
 [ 0.55685573]]


In [25]:
"""Τεστ ορθής λειτουργίας predict"""
from sklearn.datasets import make_blobs

# δημιουργία δύο ομάδων από τυχαία σημεία με κέντρο 0,0,0 και 3,3,3 και τυπική απόκλιση 1
centers = [[0.0, 0.0, 0.0], [3.0, 3.0, 3.0]]
X, y = make_blobs(n_samples=200, centers=centers,
                  random_state=47, shuffle=False)
y = np.array(y).reshape(-1,1)

lr = MyLogisticRegression()
lr.fit(X, y)
predictions = lr.predict(X[[0,199],:])
print(predictions)

assert np.allclose(lr.predict(X[[0,199],:]), np.array([[0],[1]]))

[[0]
 [1]]


## Μέρος Γ: Ομαλοποίηση (3 μονάδες)

**Γ1:** Υλοποιήστε κλάση για τον αλγόριθμο της λογιστικής παλινδρόμησης που να υποστηρίζει και ομαλοποίηση L1 και L2. Αρχικοποιήστε τις παραμέτρους σε μηδενικές τιμές. Αποθηκεύστε τες στο διάνυσμα στήλη theta. Η συνάρτηση fit πρέπει να δέχεται πίνακα X με τις τιμές των μεταβλητών εισόδου και διάνυσμα στήλη y με τις τιμές της μεταβλητής εξόδου. Ακολουθούν τεστ ορθής λειτουργίας.

In [26]:
class MyLogisticRegression:
    def __init__(self, num_iterations=2000, learning_rate=0.004, penalty="None", l=10):
        self.theta = None
        self.num_iterations = num_iterations
        self.learning_rate = learning_rate
        self.penalty = penalty
        self.l = l

    def fit(self, X, y):
        # YOUR CODE HERE
        m, n = X.shape
        X = np.concatenate((np.ones((m, 1)), X), axis=1)  # Προσθήκη της στήλης με τιμές 1 στην αρχή του X
        self.theta = np.zeros((n+1, 1))

        for _ in range(self.num_iterations):
             theta_temp = self.theta.copy()
             update = np.zeros(n+1)
             z = np.dot(X, self.theta)
             s = self.sigmoid(z)


             if self.penalty == "L1":
                 self.theta[0] -= self.learning_rate * (1 / m) * np.dot(X[:, 0].T, (s - y))
                 for j in range(1, n+1):
                    self.theta[j] -= self.learning_rate * (1 / m) * ((np.dot(X[:, j].T, (s - y)) + (self.l) * np.sign(self.theta[j])))
             elif self.penalty == "L2":
                  self.theta[0] -= self.learning_rate * (1 / m) * np.dot(X[:, 0].T, (s - y))
                  for j in range(1, n+1):
                     self.theta[j] -= self.learning_rate * (1 / m) * ((np.dot(X[:, j].T, (s - y))  + ( self.l ) * self.theta[j]))
             else:
                  self.theta = self.theta - self.learning_rate * (1 / m) * (X.T @ (self.sigmoid(X @ self.theta) - y)) # Από ερώτημα Β2


    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))


    def predict(self, X):
        m = X.shape[0]
        X = np.concatenate((np.ones((m, 1)), X), axis=1)  # Προσθήκη της στήλης με τιμές 1 στην αρχή του X
        z = np.dot(X, self.theta)
        probabilities = self.sigmoid(z)
        predictions = (probabilities >= 0.5).astype(int) # sigmoid --> Threshold 0.5
        return predictions


In [27]:
"""Τεστ ορθής λειτουργίας fit L2"""
from sklearn.datasets import make_blobs

# δημιουργία δύο ομάδων από τυχαία σημεία με κέντρο 0,0,0 και 3,3,3 και τυπική απόκλιση 1
centers = [[0.0, 0.0, 0.0], [3.0, 3.0, 3.0]]
X, y = make_blobs(n_samples=200, centers=centers,
                  random_state=47, shuffle=False)
y = np.array(y).reshape(-1,1)

lr = MyLogisticRegression(penalty="L2", l=10)
lr.fit(X, y)
print(lr.theta)
assert np.allclose(lr.theta, np.array([[-1.148294],[0.46202407],[0.38788976],[0.50990465]]))
lr = MyLogisticRegression(penalty="L2", l=100)
lr.fit(X, y)
print(lr.theta)
assert np.allclose(lr.theta, np.array([[-0.95841014],[0.30961435],[0.29482345],[0.33574242]]))

[[-1.148294  ]
 [ 0.46202407]
 [ 0.38788976]
 [ 0.50990465]]
[[-0.95841014]
 [ 0.30961435]
 [ 0.29482345]
 [ 0.33574242]]


In [28]:
"""Τεστ ορθής λειτουργίας fit L1"""
from sklearn.datasets import make_blobs

# δημιουργία δύο ομάδων από τυχαία σημεία με κέντρο 0,0,0 και 3,3,3 και τυπική απόκλιση 1
centers = [[0.0, 0.0, 0.0], [3.0, 3.0, 3.0]]
X, y = make_blobs(n_samples=200, centers=centers,
                  random_state=47, shuffle=False)
y = np.array(y).reshape(-1,1)

lr = MyLogisticRegression(penalty="L1", l=100)
lr.fit(X, y)
print(lr.theta)
assert np.allclose(lr.theta, np.array([[-0.39128777],[0.07264989],[0.06445718],[0.2047192]]))

[[-0.39128777]
 [ 0.07264989]
 [ 0.06445718]
 [ 0.2047192 ]]
